name: Docker Image Test

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Pull Docker Image from Docker Hub
      run: docker pull midralab/generate-image-api-for-lcm:latest

    - name: Run Docker Image
      run: docker run --rm midralab/generate-image-api-for-lcm:latest

    # モデルファイルの存在を確認
    - name: List Model Files
      run: |
        docker run --rm midralab/generate-image-api-for-lcm:latest bash -c "ls /usr/src/app"
